server.port:
  18080

# spring:
#   datasource:
#     url: jdbc:postgresql://127.0.0.1:5432/postgres?currentSchema=medical_db
#     username: postgres
#     password: pwd123
#     driver-class-name: org.postgresql.Driver

  # 可选：连接池配置
#  hikari:
#    minimum-idle: 5
#    maximum-pool-size: 20
#    idle-timeout: 30000
#    pool-name: HikariCP
#    max-lifetime: 60000
#    connection-timeout: 30000
# aiengine:
#   api_url: https://api.x.ai/v1/chat/completions
#   mykey:
#   max_tokens: 5000
#   temperature: 0.3
#   model: grok-3-latest
aiengine:
  api_url: https://ark.cn-beijing.volces.com/api/v3/chat/completions
  mykey: 
  max_tokens: 5000
  temperature: 0.3
  model: doubao-seed-1-6-250615